period: LifecyclePeriod

stages:

  labour_mkt_decision:
    methods:
      - on: cntn_to_dcsn_mover
        schemes:
          - scheme: branching_aggregator
            method: !max

  work_cons:
    methods:
      - on: cntn_to_dcsn_mover
        schemes:
          - scheme: bellman_backward
            method: !egm

          - scheme: interpolation
            method: !Cartesian
            settings:
              orders: [n_w]
              bounds: [[w_min, w_max]]

          - scheme: upper_envelope
            method: !FUES
            settings:
              m_bar: m_bar

  retire_cons:
    methods:
      - on: cntn_to_dcsn_mover
        schemes:
          - scheme: bellman_backward
            method: !egm

          - scheme: interpolation
            method: !Cartesian
            settings:
              orders: [n_w_ret]
              bounds: [[w_ret_min, w_ret_max]]
